version: '3'

services:

  prod:
    container_name: reward-performance-review-prod
    build:
      context: .
      args:
        - CI_BUILD_ID=${CI_BUILD_ID}
        - CI_BUILD_REF=${CI_BUILD_REF}
        - CI_BUILD_REF_NAME=${CI_BUILD_REF_NAME}
        - CI_BUILD_TIME=${CI_BUILD_TIME}
        - CI_REGISTRY_IMAGE=${CI_REGISTRY_IMAGE}
        - CI_PROJECT_NAME=${CI_PROJECT_NAME}
    image: scarlin90/reward-performance-review:prod
    environment:
      VIRTUAL_HOST: 
      HTTPS_METHOD: noredirect # support both http and https
    ports:
      - "80"
    restart: unless-stopped
    # to get this work with https://github.com/jwilder/nginx-proxy
    # related: https://github.com/jwilder/nginx-proxy/issues/305
    network_mode: bridge
